/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApuestasRouteImport } from './routes/apuestas'
import { Route as ModRouteImport } from './routes/mod'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ResueltasRouteImport } from './routes/resueltas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApuestasRoute = ApuestasRouteImport.update({
  id: '/apuestas',
  path: '/apuestas',
  getParentRoute: () => rootRouteImport,
} as any)
const ModRoute = ModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResueltasRoute = ResueltasRouteImport.update({
  id: '/resueltas',
  path: '/resueltas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apuestas': typeof ApuestasRoute
  '/mod': typeof ModRoute
  '/privacidad': typeof PrivacidadRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/resueltas': typeof ResueltasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apuestas': typeof ApuestasRoute
  '/mod': typeof ModRoute
  '/privacidad': typeof PrivacidadRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/resueltas': typeof ResueltasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apuestas': typeof ApuestasRoute
  '/mod': typeof ModRoute
  '/privacidad': typeof PrivacidadRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/resueltas': typeof ResueltasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apuestas'
    | '/mod'
    | '/privacidad'
    | '/profile'
    | '/ranking'
    | '/resueltas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apuestas'
    | '/mod'
    | '/privacidad'
    | '/profile'
    | '/ranking'
    | '/resueltas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apuestas'
    | '/mod'
    | '/privacidad'
    | '/profile'
    | '/ranking'
    | '/resueltas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApuestasRoute: typeof ApuestasRoute
  ModRoute: typeof ModRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  ResueltasRoute: typeof ResueltasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apuestas': {
      id: '/apuestas'
      path: '/apuestas'
      fullPath: '/apuestas'
      preLoaderRoute: typeof ApuestasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod': {
      id: '/mod'
      path: '/mod'
      fullPath: '/mod'
      preLoaderRoute: typeof ModRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resueltas': {
      id: '/resueltas'
      path: '/resueltas'
      fullPath: '/resueltas'
      preLoaderRoute: typeof ResueltasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApuestasRoute: ApuestasRoute,
  ModRoute: ModRoute,
  PrivacidadRoute: PrivacidadRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  ResueltasRoute: ResueltasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
